language: csharp
solution: DiscordBot4MeCoreSolution.sln
mono: none
dotnet: 2.1.503
script:
  - dotnet build -c Release
  - dotnet test DiscordBot4MeCore.xUnit.Tests/DiscordBot4MeCore.xUnit.Tests.csproj
