language: csharp
mono: none
dotnet: 2.1.503
git:
  quiet: true
jobs:
  include:
    - stage: build
      script: dotnet build -c Release
    - stage: test
      script: dotnet test DiscordBot4MeCore.xUnit.Tests/DiscordBot4MeCore.xUnit.Tests.csproj
