version: 1.0.{build}
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
image: Visual Studio 2017 Preview
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  nuget restore
  
  nuget install opencover
  
  nuget install codecov
build_script:
- ps: dotnet build -c Release
test_script:
- ps: OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test" -output:".\coverage.xml" -oldStyle -filter:"+[DiscordBot4MeCore*]* -[DiscordBot4MeCore.xUnit.Tests]*"
after_test:
- ps: .\codecov -f "coverage.xml" -t $CODECOV_TOKEN
