version: 1.0.{build}
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
image: Visual Studio 2017 Preview
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  nuget restore
  
  nuget install opencover
  
  nuget install codecov
build_script:
- ps: dotnet build -c Release
test_script:
- ps: OpenCover.Console.exe 
      -register:user 
      -target:"C:\Program Files\dotnet\dotnet.exe" 
      -targetargs:"test UnitTests.xUnit/UnitTests.xUnit.csproj" 
      -output:".\coverage.xml" 
      -oldStyle 
      -filter:"+[DiscordBot4MeCore*]* -[UnitTests.xUnit*]*"
- bash:
    curl -s https://codecov.io/bash > codecov
  
    chmod +x codecov
  
    ./codecov.sh -f "coverage.xml" -t $CODECOV_TOKEN
